### ISSUE TITLE
Format and Sort Using Doesn't Work on .Net Core Project - Visual Studio 2015

### ISSUE THREAD

**Issue by romeoDo** [Microsoft/VS-PPT#127]
Hi guys,

I am aware that the issue had been fixed in PPT 2017 but what about the PPT 2015?. Can someone make a fix for 2015 version? 

Cheers!

P/S: I don't use reshaper

**Comment by justcla** [comment]
Hi Romeo. We will probably not get around to updating the VS2015 version, as we are forging forward making fixes and improvements to the VS2017 versions.

Upgrade! VS2017 is awesome!! :-D

**Comment by romeoDo** [comment]
Hi Justcla, 

Due to the complication of my project, I will not be able to upgrade to VS2017 right now. It is a shame!. I guess I will give these feature a miss. :(

**Comment by justcla** [comment]
I'm curious about what project features won't work with VS2017.
Often nothing is required to run in VS2017 other than updating the MinimumVisualStudioVersion in the csproj file. I usually set it to $(VisualStudioVersion) so that it works in both VS2015 and VS2017 simultaneously.

**Comment by romeoDo** [comment]
Hi Juscla, 
My project is running on the APS.net Core RC1 (referred as ASP.net 5). As my team have developed and used too many things from the old DOTNET core, it will take a while for us to move to the new DOTNET CORE. At the moment, running ASP.net 5 project on Visual studio 2017 is not possible unless you have some suggestion in this. 

On top of the PPT issue, is there any easy way that I can implement the fix in PPT 2017 for PPT 2015 version on my own?

**Comment by justcla** [comment]
@romeoDo Thanks for explaining your situation. I hope we can resolve your DOTNET core upgrade issues soon.

We are looking at open-sourcing Power Commands. If we do that, you can pull the source, make the changes and install the fix on your system.

**Comment by RakeshKumarPradhan** [comment]
Sort Field Descriptor is not working in dot net core - visual studio 2017. (the same code has been working in vs2015 - dot net 4.5.1). The error is associated with using Nest Library (5.5.0). Can someone through some hints here.

**Comment by RakeshKumarPradhan** [comment]
to add few more details ... 
The following section is giving an compilation error in dot net core (2.0) - vs2017, although the same is working fine in dot net 4.5.1 - vs2015.

Error in line - sortDesc = s => s.Field(f => f.**Year**, sort.Direction);
Error description -
SortFieldDescriptor does not contain a definition for Year. This property is present in the class VehicleItem. (same is the case with few other properties like, mileage, vehicleprice, etc, though, these are also present).

Func<SortDescriptor, IPromise<IList>> sortDesc = null;

        if (!string.IsNullOrEmpty(sort.SortBy))
        {
            char fieldName = sort.SortBy.ElementAt(0);
            switch (fieldName)
            {
                case 'B':
                case 'Y':
                    sortDesc = s => s.Field(f => f.Year, sort.Direction);
                    break;
                default:
                    sortDesc = s => s.Field(f => f.Year, sort.Direction);
                    break;
            }
        }
Let me know, if I need to furnish any further details. Any help is highly appreciated.

**Comment by RakeshKumarPradhan** [comment]
The issue is resolved. 
Direction property on Sorting type should be of type Nest.SortOrder
public class Sorting
{
	public string SortBy { get; set; }
	public Nest.SortOrder Direction { get; set; }
}

Please find the link to the post - elastic forum for further details - 
https://discuss.elastic.co/t/nest-library-error-sort-field-descriptor-does-not-contain-a-definition-for-property-type-dot-net-core-2-0/115974/13
